name: build

on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [darwin, linux]
        include:
          - os: darwin
            runner: macos-latest
            no_docker: "true"
            pack_bin: pack
          - os: linux
            runner: ubuntu-latest
            no_docker: "false"
            pack_bin: pack
    runs-on: ${{ matrix.runner }}
    env:
      PACK_BIN: ${{ matrix.pack_bin }}
      NO_DOCKER: ${{ matrix.no_docker }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.13'
      - name: Set up go env
        run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
      - name: Verify
        # disabled for windows due to format verification failing
        if: matrix.os != 'windows'
        run: make verify
      - name: Test
        run: make test
      - name: Derive pack version from branch name
        run: |
          [[ $GITHUB_REF =~ ^refs\/heads\/release/(.*)$ ]] && version=${BASH_REMATCH[1]} || version=0.0.0
          echo "::set-env name=PACK_VERSION::$version"
        shell: bash
      - name: Build
        run: make build
        env:
          PACK_BUILD: ${{ github.run_number }}
      - uses: actions/upload-artifact@v1
        with:
          name: pack-${{ matrix.os }}
          path: out/${{ env.PACK_BIN }}